package interception

type InterceptionMouseState uint16
type InterceptionFilterMouseState uint16
type InterceptionMouseFlag uint16

const (
	INTERCEPTION_MOUSE_LEFT_BUTTON_DOWN   InterceptionMouseState = 0x001
	INTERCEPTION_MOUSE_LEFT_BUTTON_UP     InterceptionMouseState = 0x002
	INTERCEPTION_MOUSE_RIGHT_BUTTON_DOWN  InterceptionMouseState = 0x004
	INTERCEPTION_MOUSE_RIGHT_BUTTON_UP    InterceptionMouseState = 0x008
	INTERCEPTION_MOUSE_MIDDLE_BUTTON_DOWN InterceptionMouseState = 0x010
	INTERCEPTION_MOUSE_MIDDLE_BUTTON_UP   InterceptionMouseState = 0x020

	INTERCEPTION_MOUSE_BUTTON_1_DOWN InterceptionMouseState = INTERCEPTION_MOUSE_LEFT_BUTTON_DOWN
	INTERCEPTION_MOUSE_BUTTON_1_UP   InterceptionMouseState = INTERCEPTION_MOUSE_LEFT_BUTTON_UP
	INTERCEPTION_MOUSE_BUTTON_2_DOWN InterceptionMouseState = INTERCEPTION_MOUSE_RIGHT_BUTTON_DOWN
	INTERCEPTION_MOUSE_BUTTON_2_UP   InterceptionMouseState = INTERCEPTION_MOUSE_RIGHT_BUTTON_UP
	INTERCEPTION_MOUSE_BUTTON_3_DOWN InterceptionMouseState = INTERCEPTION_MOUSE_MIDDLE_BUTTON_DOWN
	INTERCEPTION_MOUSE_BUTTON_3_UP   InterceptionMouseState = INTERCEPTION_MOUSE_MIDDLE_BUTTON_UP

	INTERCEPTION_MOUSE_BUTTON_4_DOWN InterceptionMouseState = 0x040
	INTERCEPTION_MOUSE_BUTTON_4_UP   InterceptionMouseState = 0x080
	INTERCEPTION_MOUSE_BUTTON_5_DOWN InterceptionMouseState = 0x100
	INTERCEPTION_MOUSE_BUTTON_5_UP   InterceptionMouseState = 0x200

	INTERCEPTION_MOUSE_WHEEL  InterceptionMouseState = 0x400
	INTERCEPTION_MOUSE_HWHEEL InterceptionMouseState = 0x800

	INTERCEPTION_FILTER_MOUSE_NONE InterceptionFilterMouseState = 0x0000
	INTERCEPTION_FILTER_MOUSE_ALL  InterceptionFilterMouseState = 0xFFFF

	INTERCEPTION_FILTER_MOUSE_LEFT_BUTTON_DOWN   InterceptionFilterMouseState = 0x001
	INTERCEPTION_FILTER_MOUSE_LEFT_BUTTON_UP     InterceptionFilterMouseState = 0x002
	INTERCEPTION_FILTER_MOUSE_RIGHT_BUTTON_DOWN  InterceptionFilterMouseState = 0x004
	INTERCEPTION_FILTER_MOUSE_RIGHT_BUTTON_UP    InterceptionFilterMouseState = 0x008
	INTERCEPTION_FILTER_MOUSE_MIDDLE_BUTTON_DOWN InterceptionFilterMouseState = 0x010
	INTERCEPTION_FILTER_MOUSE_MIDDLE_BUTTON_UP   InterceptionFilterMouseState = 0x020

	INTERCEPTION_FILTER_MOUSE_BUTTON_1_DOWN InterceptionFilterMouseState = 0x001
	INTERCEPTION_FILTER_MOUSE_BUTTON_1_UP   InterceptionFilterMouseState = 0x002
	INTERCEPTION_FILTER_MOUSE_BUTTON_2_DOWN InterceptionFilterMouseState = 0x004
	INTERCEPTION_FILTER_MOUSE_BUTTON_2_UP   InterceptionFilterMouseState = 0x008
	INTERCEPTION_FILTER_MOUSE_BUTTON_3_DOWN InterceptionFilterMouseState = 0x010
	INTERCEPTION_FILTER_MOUSE_BUTTON_3_UP   InterceptionFilterMouseState = 0x020

	INTERCEPTION_FILTER_MOUSE_BUTTON_4_DOWN InterceptionFilterMouseState = 0x040
	INTERCEPTION_FILTER_MOUSE_BUTTON_4_UP   InterceptionFilterMouseState = 0x080
	INTERCEPTION_FILTER_MOUSE_BUTTON_5_DOWN InterceptionFilterMouseState = 0x100
	INTERCEPTION_FILTER_MOUSE_BUTTON_5_UP   InterceptionFilterMouseState = 0x200

	INTERCEPTION_FILTER_MOUSE_WHEEL  InterceptionFilterMouseState = 0x400
	INTERCEPTION_FILTER_MOUSE_HWHEEL InterceptionFilterMouseState = 0x800

	INTERCEPTION_FILTER_MOUSE_MOVE InterceptionFilterMouseState = 0x1000

	INTERCEPTION_MOUSE_MOVE_RELATIVE      InterceptionMouseFlag = 0x000
	INTERCEPTION_MOUSE_MOVE_ABSOLUTE      InterceptionMouseFlag = 0x001
	INTERCEPTION_MOUSE_VIRTUAL_DESKTOP    InterceptionMouseFlag = 0x002
	INTERCEPTION_MOUSE_ATTRIBUTES_CHANGED InterceptionMouseFlag = 0x004
	INTERCEPTION_MOUSE_MOVE_NOCOALESCE    InterceptionMouseFlag = 0x008
	INTERCEPTION_MOUSE_TERMSRV_SRC_SHADOW InterceptionMouseFlag = 0x100
	INTERCEPTION_MOUSE_CUSTOM             InterceptionMouseFlag = 0x200
)

type InterceptionMouseStroke struct {
	Code        uint16
	State       uint16
	Rolling     int16
	X           int32
	Y           int32
	Information uint32
}
